services:
  postgres:
    image: postgres:16-alpine
    user: postgres
    ports:
      - 5432:5432 # postgresql://myuser:mysecret@127.0.0.1:5432/mydb?search_path=public
    volumes:
      - './.local/postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=mydb

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5480:80 # http://localhost:5480
    environment:
      - PGADMIN_DEFAULT_EMAIL=myuser@example.com # login for the UI
      - PGADMIN_DEFAULT_PASSWORD=mysecret

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    # restart: always
    # save 1 or more writes every 20 seconds to disk, in case of a crash
    command: redis-server --save 20 1 --loglevel warning --requirepass mysecret
    volumes:
      - './.local/redis:/data'

  redis_serverless:
    ports:
      - '6380:80' # http://localhost:6380
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: mytoken
      SRH_CONNECTION_STRING: 'redis://:mysecret@redis:6379'
