onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - prisma

patchedDependencies:
  react-router: patches/react-router.patch
